name: BuildIt
main: com.boveybrawlers.BuildIt.BuildIt
version: 0.9
softdepend: [AbsoluteCraft, HolographicDisplays]
commands:
    buildit:
        description: The one and only command for BuildIt
        usage: /buildit